### ISSUE TITLE
Publishing storybook to Github pages

### ISSUE THREAD

**Issue by headzoo** [deskpro/deskpro-components#10]
We can use [`@storybook/storybook-deployer`](https://github.com/storybooks/storybook-deployer) to deploy our storybook to Github pages, which would give us a cheap and easy way of having a live demo for the components. Github pages would need to be enabled in the repo.

Thoughts?

**Comment by jducro** [comment]
Completely agreed
@chroder can you enable Github pages here?

**Comment by chroder** [comment]
Yeah, let's get that going. It'll be really useful for us to be able to easily see.

I've created the `gh-pages` branch for GH pages. I guess this might complicate the process slightly... But I think we need to (similar to the other issue, to avoid committing actual compiled assets to the repos).

We can set up a webhook on some hosted function service (there are a few!) that can build automatically post-master-merge.

**Comment by headzoo** [comment]
I'm going to look into a method for shoehorning the style guide into the GH pages as well.

**Comment by chroder** [comment]
Happy to get something like https://webtask.io/ set up for this sort of thing.

**Comment by headzoo** [comment]
The initial storybook has been deployed to https://deskproapps.github.io/deskpro-components through pull request #12. I think we still want to discuss some grander plans for publishing demos and documentation, but this is a good start.

**Comment by headzoo** [comment]
@chroder I can setup/build the git hooks and build scripts if you want to create an account with webtask. Or at least I can try and see how it goes using that service.
