### ISSUE TITLE
Publishing & CDN

### ISSUE THREAD

**Issue by chroder** [deskpro/deskpro-components#102]
@headzoo and I were just talking about getting deskpro-components on a cdn.

The easiest thing looks like to use https://unpkg.com/ which will just use the npm package.

1) I understand npm publishing should be through tags/travis already but it might be broken right now for some reason. So first step is fixing that.

2) We can then build on travis and publish the built `dist/` dir with the npm package, thereby getting it usable through unpkg.com.

https://stackoverflow.com/questions/31642477/how-to-publish-a-npm-package-with-distribution-files

Add `. npmignore` where we _don't_ ignore dist/ so it get's published.

**Comment by jducro** [comment]
.npmignore is already there (otherwise npm wouldn't work)
https://github.com/deskpro/deskpro-components/blob/master/.npmignore

but we put the compile code in `lib` instead of `dist` should we just change that?

**Comment by headzoo** [comment]
I'm fine with using `lib` since it's already referenced in the DeskPRO code.

**Comment by jducro** [comment]
Auto publish on npm is fixed
css compilation added and available on CDN: https://unpkg.com/deskpro-components@1.0.3/lib/css/deskpro-components.css
(with min and no-apps variations)
