### ISSUE TITLE
Expanding props on root element only

### ISSUE THREAD

**Issue by headzoo** [deskpro/deskpro-components#35]
I just noticed something I wanted to discuss. I was trying to use the `Forms/Checkbox` component like this:

```jsx
<Forms.Checkbox style={{marginBottom: 0}}>Label</Forms.Checkbox>
```

Which doesn't have the expected effect, because the props are not being expanded on the root element, but instead are expanded on a child element. As seen in the component render method.

```jsx
    const { children, className, value, ...elementProps } = this.props;
    return (
      <div
        className={classNames(
        'dp-input--checkbox',
        className,
        { 'dp-input--checkbox--disabled': this.props.disabled }
        )}
        >
        <input
          type="checkbox"
          value={value}
          id={this.id}
          onChange={this.handleChange}
          {...elementProps}
          />
        <label htmlFor={this.id} className="dp-input--checkbox__checkbox" />
        <Label htmlFor={this.id}>{children}</Label>
      </div>
    )
```

To me that behavior seems counter intuitive, because I expect styles set on the component, e.g. `<Forms.Checkbox />`, to affect the component as a whole, and not a smaller element within the component. I think props should always be expanded on the root element, and special props can be passed to child elements.

For instance in `Forms/Checkbox` there could be a `inputStyles` prop that gets passed to the `<input />` element.

```jsx
    const { children, className, inputStyles, value, ...elementProps } = this.props;
    return (
      <div
        className={classNames(
        'dp-input--checkbox',
        className,
        { 'dp-input--checkbox--disabled': this.props.disabled }
        )}
        {...elementProps}
        >
        <input
          type="checkbox"
          value={value}
          id={this.id}
          onChange={this.handleChange}
          style={inputStyles}
          />
        <label htmlFor={this.id} className="dp-input--checkbox__checkbox" />
        <Label htmlFor={this.id}>{children}</Label>
      </div>
    )
```

**Comment by jducro** [comment]
We don't use much styling via javascript here so that's not usually a problem we encounter.
My approach here was more that the `Checkbox` component should behave like it was just the `input` element so you could set _required_, _disable_ or _checked_ or _defaultChecked_
What I would do them to solve your problem would be:
```jsx
    const { children, className, inputStyles, style, value, ...elementProps } = this.props;
    return (
      <div
        className={classNames(
        'dp-input--checkbox',
        className,
        { 'dp-input--checkbox--disabled': this.props.disabled }
        )}
       style={style}
        >
        <input
          type="checkbox"
          value={value}
          id={this.id}
          onChange={this.handleChange}
          style={inputStyles}
          {...elementProps}
          />
        <label htmlFor={this.id} className="dp-input--checkbox__checkbox" />
        <Label htmlFor={this.id}>{children}</Label>
      </div>
    )
```

What do you think?

**Comment by headzoo** [comment]
Yep, you're right. The vast majority of props passed to the `Checkbox` component need to be set on the `checkbox` element. Your solution to pass the `style` prop to the root element works for me.
